services:
  frontend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    restart: unless-stopped
    command: tail -f /dev/null
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    restart: unless-stopped